name: Auto Tag by Environment

on:
  push:
    branches:
      - dev
      - stage
      - prod
      - test

jobs:
  tag-version:
    runs-on: windows-latest
    permissions:
      contents: write  # required to push tags

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment name
        id: set-env
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "ENVIRONMENT=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Generate and push tag
        run: |
          ENV=${{ steps.set-env.outputs.ENVIRONMENT }}
          VERSION="${ENV}-v$(date +%Y%m%d%H%M%S)"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "$VERSION"
          git push origin "$VERSION"
