name: Auto Tag and Test by Environment

on:
  push:
    branches:
      - -main
      - dev
      - stage
      - prod
      - test
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 9 * * *'  # Runs daily at 09:30 UTC
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  tag-version:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment name
        id: set-env
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "ENVIRONMENT=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Generate and push tag
        run: |
          ENV=${{ steps.set-env.outputs.ENVIRONMENT }}
          VERSION="${ENV}-v$(date +%Y%m%d%H%M%S)"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "$VERSION"
          git push origin "$VERSION"

  run-tests:
    needs: tag-version
    runs-on: ubuntu-latest
    env:
      PARABANK_URL: ${{ secrets.PARABANK_URL }}
      DEV_USERNAME1: ${{ secrets.DEV_USERNAME1 }}
      DEV_PASSWORD1: ${{ secrets.DEV_PASSWORD1 }}
      STG_USERNAME1: ${{ secrets.STG_USERNAME1 }}
      STG_PASSWORD1: ${{ secrets.STG_PASSWORD1 }}
      TEST_USERNAME1: ${{ secrets.TEST_USERNAME1 }}
      TEST_PASSWORD1: ${{ secrets.TEST_PASSWORD1 }}
      NODE_ENV: ${{ github.ref_name }}  # sets NODE_ENV as branch name

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test src/tests/ParaBankLogin.spec.js --config=playwright.config.js --project=chromium

      - name: Upload Playwright Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report  #artifact name
          path: playwright-report/
          retention-days: 7