on:
  push:
    branches:
      - main
jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate tag
        run: |
          VERSION="e2e-v$(date +%Y%m%d%H%M%S)"
          git tag $VERSION
          git push origin $VERSION
