name: Playwright UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      BASEURL: ${{ secrets.BASEURL }}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      SECRET: ${{ secrets.SECRET }}
      SECRETOTP: ${{ secrets.SECRETOTP }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 #it will get the code from the working-directory: and it can be used in subsequent step.

      - name: Setup Node.js
        uses: actions/setup-node@v4 #stes the node.js in the env
        with:
          node-version: 18 #install latest node.js version.[long term support]

      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-chromium

      - name: Install Dependencies
        run: npm ci # Faster and ensures dependencies match package-lock.json

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Check Playwright Version
        run: npx playwright --version

      - name: Run Playwright UI Test
        run:  npx playwright test tests/TrelloBoard/Templates/E2E-Tests/1-on-1MeetingAgenda.spec.js --config=playwright.config.js --project=chromium

      - name: Clean previous Allure results
        shell: pwsh
        run: |
          Remove-Item ./allure-results/* -Recurse -Force        

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 7