name: Playwright API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 9 * * *'  # Runs daily at 09:30 UTC
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 #it will get the code from the working-directory: and it can be used in subsequent step.

      - name: Setup Node.js
        uses: actions/setup-node@v4 #stes the node.js in the env
        with:
          node-version: 18 #install latest node.js version.[long term support]

      - name: Install Dependencies
        run: npm ci  # Faster and ensures dependencies match package-lock.json

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Run Playwright Tests
        run: npx playwright test tests/API-TESTING --config=playwright.config.js --project=chromium

      - name: Upload Playwright Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report  #artifact name
          path: playwright-report/
          retention-days: 7
